function w = NBgen_white_excite(NBw,N,Ts,flag_plot)
% Narrow band signals generated by white noise excitation
% function w = NBgen_white_excite(NBw,N,Ts)
% ============================================================
%   Copyright (c) 2008-, Xu Chen, xuchen@cal.berkeley.edu
%   Author(s): Xu Chen 
% ============================================================
if nargin < 4
    flag_plot = 'noplot';
end

alpha = 1;
lb1true = 2*cos(NBw(1)*Ts);
lb2true = 2*cos(NBw(2)*Ts);
eta1 = -(lb1true+lb2true);
eta2 = 2+lb1true*lb2true;

W = tf(...
    [1 0 0 0 0],...
    [1 +alpha*eta1 alpha^2*eta2 +alpha^3*eta1 alpha^4],...
    Ts);% Internal Model

d = randn(N,1)/1e7; % excitation white noise
w = lsim(W,d);

e = lsim(1/W,w);
if strcmpi (flag_plot,'plot')
    figure;plot(w);title 'generated narrow band disturbance';
    
    figure;plot(e);title 'narrow band disturbance passed the internal model';
    
    figure;plot(d);title 'excitation white noise';
end